### ISSUE TITLE
Couldn't remove comma and dot from android keyboard

### ISSUE THREAD

**Issue by NitiLTechscape** [sanifhimani/flutter_pin_code_fields#11]
I have set keyboardType to TextInputType.numberWithOptions(signed: false, decimal: false) but on android it still on keyboard and there is no inputFormatters for incoming input.
sorry for my english.
![Screenshot_1676947690](https://user-images.githubusercontent.com/116702363/220234937-593d34df-bbf9-4ca1-a069-92ac3a813d7c.png)

**Comment by sanifhimani** [comment]
I'm not sure why this would happen. It looks like this isn't working for a regular text field too.
Anyway, I added support for input formatters with [v2.1.0](https://github.com/sanifhimani/flutter_pin_code_fields/releases/tag/v2.1.0) so you can do something like this:

```dart
PinCodeFields(
  keyboardType: TextInputType.number,
  inputFormatters: [FilteringTextInputFormatter.digitsOnly],
)
```
