### ISSUE TITLE
Flutter Web - Not accepting keyboard inputs

### ISSUE THREAD

**Issue by DurgeshSawantWYLD** [sanifhimani/flutter_pin_code_fields#6]
Seems the package isn't working on flutter web.
cannot enter anything from the physical or virtual on-screen keyboard into the code fields 
Please help out.

Thanks in advance..

**Comment by sanifhimani** [comment]
Fixed with [tag-v2.0.0](https://github.com/sanifhimani/flutter_pin_code_fields/releases/tag/v2.0.0)
